// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBoWdbdSUdPMKmu5U03KZKElCdflQ8HIgk',
    appId: '1:736538351274:web:b6c7dcd8b625b0602662d3',
    messagingSenderId: '736538351274',
    projectId: 'korastudy-9b3d5',
    authDomain: 'korastudy-9b3d5.firebaseapp.com',
    storageBucket: 'korastudy-9b3d5.firebasestorage.app',
    measurementId: 'G-F7CW9T1XR5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAUrEy1FaUD9UlxYdi68cuh52KceCDeJBg',
    appId: '1:736538351274:android:7f630ae85e0235682662d3',
    messagingSenderId: '736538351274',
    projectId: 'korastudy-9b3d5',
    storageBucket: 'korastudy-9b3d5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD8tb3B-SdNiRk2sHYf0eyQwUHhJfElGpw',
    appId: '1:736538351274:ios:7f2f2dbad34fcf442662d3',
    messagingSenderId: '736538351274',
    projectId: 'korastudy-9b3d5',
    storageBucket: 'korastudy-9b3d5.firebasestorage.app',
    androidClientId: '736538351274-0f38m2154qbtghodm8amp6vun7ps428e.apps.googleusercontent.com',
    iosClientId: '736538351274-pqmg9anjp0luodoav1h5tokk1mp3n20h.apps.googleusercontent.com',
    iosBundleId: 'com.example.korastudyFe',
  );
}
